#!/usr/bin/env python3
"""Convert a SimpleArmory JSON data file into a Lua table for the addon.

The output file defines a single global table `SimpleCollectionData` that the
addon consumes directly, so no JSON parsing has to happen at runtime in game.

Usage: json2lua.py <input.json> <output.lua>
"""
import json
import sys

INDENT = "  "


def escape_string(value):
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )


def to_lua(value, depth=0):
    pad = INDENT * depth
    child_pad = INDENT * (depth + 1)
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return '"%s"' % escape_string(value)
    if isinstance(value, list):
        if not value:
            return "{}"
        parts = ["%s%s," % (child_pad, to_lua(item, depth + 1)) for item in value]
        return "{\n%s\n%s}" % ("\n".join(parts), pad)
    if isinstance(value, dict):
        # Keys with null values are dropped; in Lua a missing key reads as nil anyway.
        entries = [
            '%s["%s"] = %s,' % (child_pad, escape_string(str(key)), to_lua(item, depth + 1))
            for key, item in value.items()
            if item is not None
        ]
        if not entries:
            return "{}"
        return "{\n%s\n%s}" % ("\n".join(entries), pad)
    raise TypeError("unsupported JSON type: %r" % type(value))


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: json2lua.py <input.json> <output.lua>")
    with open(sys.argv[1], encoding="utf-8") as handle:
        data = json.load(handle)
    with open(sys.argv[2], "w", encoding="utf-8", newline="\n") as handle:
        handle.write("-- Generated by tools/json2lua.py from SimpleArmory data - do not edit.\n")
        handle.write("SimpleCollectionData = %s\n" % to_lua(data))


if __name__ == "__main__":
    main()
