name: Build data.lua and Release Addon

on:
  schedule:
    - cron: "0 0 2 * *"   # Läuft am 2. Tag jedes Monats um 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download mounts.json
        run: curl -sL https://raw.githubusercontent.com/kevinclement/SimpleArmory/master/static/data/mounts.json -o mounts.json

      - name: Create data.lua
        run: |
          mkdir -p data
          {
            echo 'SimpleCollectionData = [['
            echo '    {'
            echo '        "id": "xxallxx",'
            echo '        "name": "AllMounts",'
            echo '        "all": '
            cat mounts.json
            echo '}'
            echo ']]'
          } > data/data.lua

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/data.lua
          git commit -m "Update data.lua from mounts.json" || echo "No changes to commit"
          git push

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "SimpleCollection v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Zip Addon for Release
        run: |
          zip -r SimpleCollection.zip . -x ".git/*" -x "*.github/*"

      - name: Upload Addon ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SimpleCollection.zip
          asset_name: SimpleCollection.zip
          asset_content_type: application/zip
