name: Build data.lua

on:
  schedule:
    - cron: "0 0 2 * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download mounts.json
        run: curl -sL https://raw.githubusercontent.com/kevinclement/SimpleArmory/master/static/data/mounts.json -o mounts.json

      - name: Create data.lua
        run: |
          mkdir -p data
          {
            echo 'SimpleCollectionData = [['
            echo '    {'
            echo '        "id": "xxallxx",'
            echo '        "name": "AllMounts",'
            echo '        "all": '
            cat mounts.json
            echo '}'
            echo ']]'
          } > data/data.lua

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/data.lua
          git commit -m "Update data.lua from mounts.json" || echo "No changes to commit"
          git push
