name: Copy File Workflow

on:
  push:
    branches:
      - main  # Ändere den Branch-Namen entsprechend

jobs:
  copy_file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Copy File
      run: |
        wget https://raw.githubusercontent.com/kevinclement/SimpleArmory/master/static/data/mounts.json -O source-file
        cp source-file testfile.json
